recommender/notebooks/flask_app/skateboard/app/models.py
from app import db

class Getrecommender(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    platform = db.Column(db.String(200), nullable=False)
    modelType = db.Column(db.Text(), nullable=False)
    item = db.Column(db.String(200), nullable=False)
    eventTime = db.Column(db.DateTime(), nullable=False)



class Putrecommend(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    recommend_id = db.Column(db.Integer, db.ForeignKey('getrecommender.id', ondelete='CASCADE'))
    recommend = db.relationship('Getrecommender', backref=db.backref('item_set'))
    item = db.Column(db.String(200), nullable=False)
    eventTime = db.Column(db.DateTime(), nullable=False)


class Useritemmodel(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.String(150), unique=True, nullable=False)
    item_id = db.Column(db.String(200), nullable=False)
    model_a = db.Column(db.String(120), nullable=False)
    model_b = db.Column(db.String(120), nullable=False)
    model_c = db.Column(db.String(120), nullable=False)


class sims_reco(db.Model):
    index = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, unique=True, nullable=False)
    # item_id = db.Column(db.Integer, nullable=False)
    platform = db.Column(db.String(200), nullable=False)
    modelType = db.Column(db.Text(), nullable=False)
    recommender_id = db.Column(db.Integer, db.ForeignKey('getrecommender.id', ondelete='CASCADE'))
    top1=db.Column(db.String(120), nullable=False)
    top2=db.Column(db.String(120), nullable=False)
    top3=db.Column(db.String(120), nullable=False)
    top4=db.Column(db.String(120), nullable=False)
    top5=db.Column(db.String(120), nullable=False)
    top6=db.Column(db.String(120), nullable=False)
    top7=db.Column(db.String(120), nullable=False)
    top8=db.Column(db.String(120), nullable=False)
    top9=db.Column(db.String(120), nullable=False)
    top10=db.Column(db.String(120), nullable=False)



class user_history(db.Model):
    index = db.Column(db.Integer, primary_key=True)
    user_name=db.Column(db.String(120), nullable=False)
    user_id=db.Column(db.Integer, nullable=False)
    item_name=db.Column(db.String(120), nullable=False)
    item_id=db.Column(db.Integer, nullable=False)
    timestamp=db.Column(db.DateTime(), nullable=False)
    

recommender/notebooks/flask_app/skateboard/app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField
from wtforms.validators import DataRequired

class CompareForm(FlaskForm):
    user_id = StringField('User ID', validators=[DataRequired()])
    item_id = StringField('Item ID', validators=[DataRequired()])
    model_a = StringField('Model A', validators=[DataRequired()])
    model_b = StringField('Model B', validators=[DataRequired()])
    model_c = StringField('Model C', validators=[DataRequired()])

class useridForm(FlaskForm):
    user_id=IntegerField('User ID', validators=[DataRequired()])

recommender/notebooks/flask_app/skateboard/app/__init__.py
from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
import config, os

db = SQLAlchemy()
migrate = Migrate()

BASE_DIR = os.path.dirname(__file__)

def create_app(config):
    app = Flask(__name__)

    app.config.from_object(config)
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///{}'.format(os.path.join(BASE_DIR, 'reco.db'))
    app.config['SECRET_KEY'] = "dev"

    # 
    db.init_app(app)
    migrate.init_app(app, db)

    from . import models

    from .views import main_views, compare_views
    app.register_blueprint(main_views.bp)
    app.register_blueprint(compare_views.bp)

    return app

recommender/notebooks/flask_app/skateboard/app/views/compare_views.py
from datetime import datetime

from flask import Blueprint, url_for, request, flash, render_template, session, g
from werkzeug.utils import redirect

from app import db
from app.forms import CompareForm, useridForm
from app.models import Getrecommender, user_history, sims_reco
from ..utils import get_viewed_list, get_popular_list, get_compare_list

bp = Blueprint('compare', __name__, url_prefix='/compare')

@bp.route('/')
@bp.route('/<int:user_id>')
def input(user_id=None):
    popular_list = get_popular_list()
    return render_template('recommend/compare_detail.html', 
                                    user_id=user_id,
                                    popular_list=popular_list)


@bp.errorhandler(404)
def page_not_found(error): 
    return redirect(url_for('compare.input', user_id=None))

@bp.route('/test', methods=['POST'])
def test(user_id=None):
    if request.method == 'POST':
        user = request.form['user_id']
        session.clear()
        session['user_id'] = user
        history = user_history.query.get_or_404(user)
        reco_list, aws_list = get_compare_list(user, 'cf_reco', 'aws_reco')
        view_list = get_viewed_list(user)
        return render_template('recommend/compare_detail.html',
                                user_id=user,
                                history=history,
                                reco_list=reco_list,
                                data_list=view_list,
                                aws_list =aws_list)
    else:
        user = None
    return redirect(url_for('compare.input', user_id=user))


@bp.before_app_request
def load_reco_for_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = sims_reco.query.get(user_id)


@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('compare.input'))

recommender/notebooks/flask_app/skateboard/app/views/main_views.py
from flask import Blueprint, render_template, url_for
from werkzeug.utils import redirect
from app.models import Getrecommender

bp = Blueprint('main', __name__, url_prefix='/')


@bp.route('/hello')
def hello_recommender():
    return 'Hello, Recommender!'

@bp.route('/')
def index():
    return redirect(url_for('compare.input'))

recommender/notebooks/flask_app/skateboard/app/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
    <!-- CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    
    <title>Recommender</title>
</head>
<body>
{% include "navbar.html" %}
{% block content %}
{% endblock %}
<!-- jQuery JS -->
<script src="{{ url_for('static', filename='jquery-3.6.0.min.js') }}"></script>
<!-- Bootstrap JS -->
<script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>

</body>
</html>

recommender/notebooks/flask_app/skateboard/app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{{ url_for('compare.logout') }}">Recommender</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        {% if g.user %}
        <ul class="navbar-nav">
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('compare.logout') }}"></a>
            </li>
        </ul>
        {% else %}
        {% endif %}
    </div>
</nav>

recommender/notebooks/flask_app/skateboard/app/templates/recommend/compare_detail.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <h2 class="border-bottom py-2">Hello, Digital Lab :)</h2>
    <p>  </p><br>
    <h5>Please let us know <b>USER ID</b></h5>
        <form method="POST" action="{{ url_for('compare.test') }}">
            <input type="text" name="user_id" id="user_id" placeholder="USER ID (0~33631)">
            <button type="submit" class="btn btn-primary">Send</button>
        </form>
    <div>
        <p>
            {% if user_id == None %} 
            <br>
            <br>
            <h5>The most popular items we have </h5>
            <table class="table">
                <tbody>
                {% for pop in popular_list %}
                <tr>
                    <td>{{ loop.index }}</td>
                    <td>{{ pop.item_title }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
            <br>
            {% else %}
            <br>
            <br>
            <h5 class="border-bottom my-3 py-2">Recommended for ID:{{ user_id }} <small> [{{ history.user_name }}]</h5>
                <div class="container my-3">
                    <br>
                    <div class="row">
                        <div class="col-sm">
                            <h5 class="border-bottom my-3 py-2">D.Lab - CF</h5>
                            <div class="col col-rows-10">
                            {% for reco in reco_list %}  
                                {% if reco.is_intersection == 1 %}
                                    <div class="card border-primary mb-3">
                                    <div class="card-body"><h5 class="card-title"><small>{{ reco.item_title }}</small></h5></div>
                                    <div class="d-flex justify-content-end"></div></div><br>
                                {% else %}
                                    <div class="card">
                                    <div class="card-body"><h5 class="card-title"><small>{{ reco.item_title }}</small></h5></div>
                                    <div class="d-flex justify-content-end"></div></div><br>
                                {% endif %}
                            {% endfor %}
                            </div>
                        </div>
                        <div class="col-sm">
                            <h5 class="border-bottom my-3 py-2">AWS personalize</h5>
                            <div class="col col-rows-10">
                            {% for aws in aws_list %}
                                {% if aws.is_intersection == 1 %}
                                    <div class="card border-primary mb-3">
                                    <div class="card-body"><h5 class="card-title"><small>{{ aws.item_title }}</small></h5></div>
                                    <div class="d-flex justify-content-end"></div></div><br>
                                {% else %}
                                    <div class="card">
                                    <div class="card-body"><h5 class="card-title"><small>{{ aws.item_title }}</small></h5></div>
                                    <div class="d-flex justify-content-end"></div></div><br>
                                {% endif %}
                            {% endfor %}
                            </div>
                        </div>
                        <div class="col-sm">
                            <h5 class="border-bottom my-3 py-2">Recently viewed</h5>
                            <div class="col col-rows-10">
                            {% for obj in data_list %}
                                <div class="card">
                                <div class="card-body"><h5 class="card-title"><small>{{ obj.item_title }}</small></h5></div>
                                <div class="d-flex justify-content-end"></div></div><br>
                            {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            <br>
            {% endif %}
        </p>
    </div>
</div>
{% endblock %}